### ISSUE TITLE
lsb-sandbox applied to theme switcher

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#112]
I thought I could prevent my global styles from bleeding into storybook with this:

```css
html:not(.lsb),
body:not(.lsb),
.lsb-sandbox {
  /* ... */
}
```

However, the storybook theme dropdown also has the sandbox classes:

```html
<div class="... lsb-sandbox myapp-web">
```

Is that by design? I would have expected the sandbox classes to only be added to the containers around my own components.
